# Generated by Django 2.2.1 on 2019-05-16 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_funcion_palabras'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('ponderacion', models.IntegerField()),
                ('canal_1', models.CharField(max_length=255)),
                ('canal_2', models.CharField(max_length=255)),
                ('nombre', models.CharField(max_length=255)),
                ('nombre_audio', models.CharField(max_length=255)),
                ('fk_audio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audio', to='core.Audio')),
                ('fk_funcion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='funcion_reporte', to='core.Funcion')),
            ],
        ),
    ]
