# Generated by Django 2.2.1 on 2019-05-16 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_reporte'),
    ]

    operations = [
        migrations.AddField(
            model_name='palabras',
            name='porcentaje',
            field=models.IntegerField(default=5),
        ),
    ]
