# Generated by Django 2.2.1 on 2019-05-18 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20190518_0207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporte',
            name='nombre',
            field=models.CharField(max_length=255),
        ),
    ]
