# Generated by Django 2.2.1 on 2019-05-29 21:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20190518_0208'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcion',
            name='estado',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Habilitado'), (2, 'Deshabilitado')], default=2),
        ),
        migrations.AddField(
            model_name='funcion',
            name='porcentaje',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='funcion',
            name='frase',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='palabras',
            name='porcentaje',
            field=models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
