# Generated by Django 2.2.1 on 2019-05-29 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20190529_1810'),
    ]

    operations = [
        migrations.RenameField(
            model_name='funcion',
            old_name='porcentaje',
            new_name='ponderacion',
        ),
    ]
