# Generated by Django 2.2.1 on 2019-06-02 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20190601_2156'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaña_funciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('funciones', models.ManyToManyField(to='core.Funcion')),
            ],
        ),
        migrations.CreateModel(
            name='Campaña_Audio_Analisis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analisis', models.IntegerField()),
                ('fk_audio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_audio_campaña', to='core.Audio')),
                ('fk_campaña', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaña', to='core.Campaña')),
                ('fk_funcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_funcion_campaña', to='core.Funcion')),
            ],
            options={
                'unique_together': {('fk_audio', 'fk_funcion', 'fk_campaña')},
            },
        ),
    ]
