# Generated by Django 2.2.1 on 2019-06-02 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20190602_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaña_funciones',
            name='fk_campaña',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='fk_campaña', to='core.Campaña'),
        ),
    ]
