# Generated by Django 2.2.1 on 2019-06-02 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_campaña_funciones_fk_campaña'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaña_audio_analisis',
            name='fk_campaña_funcion',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='fk_campaña_funcion', to='core.Funcion'),
        ),
        migrations.AlterUniqueTogether(
            name='campaña_audio_analisis',
            unique_together={('fk_audio', 'fk_campaña_funcion', 'fk_campaña')},
        ),
        migrations.RemoveField(
            model_name='campaña_audio_analisis',
            name='fk_funcion',
        ),
    ]
