# Generated by Django 2.2.1 on 2019-06-02 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20190602_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaña_audio_analisis',
            name='fk_funcion',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='fk_funcion', to='core.Funcion'),
        ),
        migrations.AlterField(
            model_name='campaña_audio_analisis',
            name='fk_campaña_funcion',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='fk_campaña_funcion', to='core.Campaña_funciones'),
        ),
    ]
