# Generated by Django 2.2.1 on 2019-06-02 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20190602_1456'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='campaña_audio_analisis',
            unique_together={('fk_audio', 'fk_campaña_funcion', 'fk_campaña', 'fk_funcion')},
        ),
    ]
