# Generated by Django 2.2.1 on 2019-06-02 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20190602_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='canal_1',
            field=models.TextField(default='', max_length=4000),
        ),
        migrations.AddField(
            model_name='audio',
            name='canal_2',
            field=models.TextField(default='', max_length=4000),
        ),
    ]
