# Generated by Django 2.2.1 on 2019-06-19 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20190602_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaña_funciones',
            name='funciones',
            field=models.ManyToManyField(limit_choices_to={'estado': 1}, to='core.Funcion'),
        ),
        migrations.AlterField(
            model_name='palabras',
            name='palabra',
            field=models.CharField(max_length=30),
        ),
    ]
