# Generated by Django 2.2.1 on 2019-06-26 00:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    atomic = False
    dependencies = [
        ('core', '0019_auto_20190619_1141'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Campaña_funciones',
            new_name='Analisis',
        ),
        migrations.AddField(
            model_name='reporte',
            name='fk_analisis',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='fk_analisis', to='core.Analisis'),
        ),
        migrations.AlterUniqueTogether(
            name='reporte',
            unique_together={('fk_audio', 'fk_analisis', 'fk_funcion')},
        ),
        migrations.DeleteModel(
            name='Campaña_Audio_Analisis',
        ),
    ]
