# Generated by Django 2.2.1 on 2019-06-26 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20190625_2202'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reporte',
            old_name='nombre',
            new_name='nombre_agente',
        ),
        migrations.AddField(
            model_name='reporte',
            name='fecha_audio',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='reporte',
            name='nombre_campaña',
            field=models.CharField(default=None, max_length=80),
        ),
    ]
