# Generated by Django 2.2.1 on 2019-06-27 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20190626_0237'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='comentario',
            field=models.TextField(default='', max_length=10000),
        ),
        migrations.AddField(
            model_name='reporte',
            name='comentario',
            field=models.TextField(default='', max_length=10000),
        ),
    ]
