# Generated by Django 2.2.1 on 2019-07-04 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_auto_20190703_2359'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaña',
            name='funciones',
            field=models.ManyToManyField(limit_choices_to={'estado': 1}, to='core.Funcion'),
        ),
    ]
