# Generated by Django 2.2.1 on 2019-08-10 23:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_auto_20190728_2317'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='procesado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='audio',
            name='agente',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agente', to='core.Agente'),
        ),
        migrations.AlterField(
            model_name='audio',
            name='campaña',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campaña_audio', to='core.Campaña'),
        ),
    ]
