# Generated by Django 2.2.1 on 2019-08-13 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_auto_20190810_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='agente',
            name='idMitrol',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='audio',
            name='fileOriginal',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='campaña',
            name='idMitrol',
            field=models.IntegerField(default=0),
        ),
    ]
