# Generated by Django 2.2.1 on 2019-09-16 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_auto_20190813_0111'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='canalOrdenado',
            field=models.TextField(default='', max_length=25000),
        ),
    ]
