# Generated by Django 2.2.1 on 2019-09-16 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_audio_canalordenado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reporte',
            name='canal_1',
        ),
        migrations.RemoveField(
            model_name='reporte',
            name='canal_2',
        ),
        migrations.AddField(
            model_name='reporte',
            name='canalOrdenado',
            field=models.TextField(default='', max_length=25000),
        ),
    ]
